apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dewflow-api
  namespace: dewflow
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: dewflow.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dewflow-api
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dewflow-frontend
  namespace: dewflow
spec:
  ingressClassName: nginx
  rules:
    - host: dewflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dewflow-frontend
                port:
                  name: http
