apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - knowledge-files-pvc.yaml
  - db-migrator-job.yaml
  - api-deployment.yaml
  - api-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - api-hpa.yaml
  - worker-deployment.yaml
  - worker-keda-scaledobject.yaml
  - credit-scheduler-deployment.yaml
