"""change id to ulid

Revision ID: c10897ad7ae7
Revises: 93e33503f942
Create Date: 2026-01-08 22:37:41.097330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import MetaData
convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "%(table_name)s_pkey"
}
metadata = MetaData(naming_convention=convention)

# revision identifiers, used by Alembic.
revision: str = 'c10897ad7ae7'
down_revision: Union[str, Sequence[str], None] = '93e33503f942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_new',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_new_username'), 'user_new', ['username'], unique=True)
    # ### end Alembic commands ###
# 2. 存量数据搬迁 (Data Seeding)
    # 利用 SQL 直接在数据库内部完成转换，效率最高
    op.execute("""
        INSERT INTO user_new (id, username, email, old_id)
        SELECT 
            (lpad(to_hex(id), 32, '0')::uuid), -- 保持确定性转换
            username, 
            email, 
            id 
        FROM public.user
    """)
    # === 开始交换 ===
    
    # 1. 交换表名
    op.rename_table('user', 'user_backup')
    op.rename_table('user_new', 'user')

    # 2. 处理主键 (PK)
    # 把旧表的主键让出来
    op.execute('ALTER TABLE "user_backup" RENAME CONSTRAINT "user_pkey" TO "user_backup_pkey"')
    # 把新表的主键(假设叫 user_new_pkey) 改正为 user_pkey
    op.execute('ALTER TABLE "user" RENAME CONSTRAINT "user_new_pkey" TO "user_pkey"')

    # 3. 处理唯一约束 (Unique)
    # 假设有个 unique=True 的字段 email，约束名叫 uq_user_email
    op.execute('ALTER TABLE "user_backup" RENAME CONSTRAINT "user_email_key" TO "uq_user_backup_email"')
    op.execute('ALTER TABLE "user" RENAME CONSTRAINT "uq_user_new_email" TO "uq_user_email"')

    # 4. 处理普通索引 (Index)
    op.execute('ALTER INDEX "ix_user_username" RENAME TO "ix_user_backup_username"')
    op.execute('ALTER INDEX "ix_user_new_username" RENAME TO "ix_user_username"')
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table('user', 'user_new')
    op.rename_table('user_backup', 'user')

    op.drop_table('user_new')
    op.execute('ALTER TABLE "user" RENAME CONSTRAINT "user_backup_pkey" TO "user_pkey"')
    op.execute('ALTER TABLE "user" RENAME CONSTRAINT "uq_user_backup_email" TO "user_email_key"')
    op.execute('ALTER INDEX "ix_user_backup_username" RENAME TO "ix_user_username"')
    # ### end Alembic commands ###
