"""Table structure fine-tuning

Revision ID: 678e5c0abf31
Revises: 2207686616a6
Create Date: 2026-03-09 21:28:20.185021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '678e5c0abf31'
down_revision: Union[str, Sequence[str], None] = '2207686616a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_files',
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='基于ULID生成的唯一标识'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('fk_knowledge_files_kb_id_knowledge_bases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_files_pkey'))
    )
    op.create_index(op.f('ix_knowledge_files_kb_id'), 'knowledge_files', ['kb_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('source_type', sa.String(length=20), server_default='file', nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='基于ULID生成的唯一标识'),
    sa.CheckConstraint('(file_id IS NOT NULL)::int + (message_id IS NOT NULL)::int = 1', name=op.f('ck_document_chunks_ck_chunk_exactly_one_source')),
    sa.ForeignKeyConstraint(['file_id'], ['knowledge_files.id'], name=op.f('fk_document_chunks_file_id_knowledge_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_document_chunks_message_id_chat_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey'))
    )
    op.create_index('hnsw_idx_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_document_chunks_file_id'), 'document_chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_message_id'), 'document_chunks', ['message_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_source_type'), 'document_chunks', ['source_type'], unique=False)
    op.drop_index(op.f('hnsw_idx_file_chunks_embedding'), table_name='file_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_table('file_chunks')
    op.drop_table('files')
    op.alter_column(
        'chat_sessions',
        'model_config',
        new_column_name='llm_config',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.create_index(op.f('ix_chat_sessions_kb_id'), 'chat_sessions', ['kb_id'], unique=False)
    op.drop_constraint(op.f('fk_chat_sessions_kb_id_knowledge_bases'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chat_sessions_kb_id_knowledge_bases'), 'chat_sessions', 'knowledge_bases', ['kb_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_knowledge_bases_user_id'), 'knowledge_bases', ['user_id'], unique=False)
    op.create_index(op.f('ix_task_jobs_action_type'), 'task_jobs', ['action_type'], unique=False)
    op.create_index(op.f('ix_task_jobs_status'), 'task_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_jobs_status'), table_name='task_jobs')
    op.drop_index(op.f('ix_task_jobs_action_type'), table_name='task_jobs')
    op.drop_index(op.f('ix_knowledge_bases_user_id'), table_name='knowledge_bases')
    op.alter_column(
        'chat_sessions',
        'llm_config',
        new_column_name='model_config',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_constraint(op.f('fk_chat_sessions_kb_id_knowledge_bases'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_chat_sessions_kb_id_knowledge_bases'), 'chat_sessions', 'knowledge_bases', ['kb_id'], ['id'])
    op.drop_index(op.f('ix_chat_sessions_kb_id'), table_name='chat_sessions')
    op.create_table('files',
    sa.Column('kb_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False, comment='基于ULID生成的唯一标识'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('fk_files_kb_id_knowledge_bases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('files_pkey'))
    )
    op.create_table('file_chunks',
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False, comment='基于ULID生成的唯一标识'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_file_chunks_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('file_chunks_pkey'))
    )
    op.create_index(op.f('hnsw_idx_file_chunks_embedding'), 'file_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_document_chunks_source_type'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_message_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_file_id'), table_name='document_chunks')
    op.drop_index('hnsw_idx_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_knowledge_files_kb_id'), table_name='knowledge_files')
    op.drop_table('knowledge_files')
    # ### end Alembic commands ###
