"""add_credits_tables

Revision ID: ee8c06050a97
Revises: e5a1b2c3d4f5
Create Date: 2026-05-22 15:28:46.529199

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ee8c06050a97'
down_revision: str | Sequence[str] | None = 'e5a1b2c3d4f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联的用户ID'),
    sa.Column('balance', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Credits 余额(以最小单位记，防精度丢失)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='基于ULID生成的唯一标识'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_accounts_pkey'))
    )
    op.create_index(op.f('ix_credit_accounts_user_id'), 'credit_accounts', ['user_id'], unique=True)
    op.create_table('credit_transactions',
    sa.Column('account_id', sa.UUID(), nullable=False, comment='关联的 Credit 账户ID'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='变动数额(正为加，负为减)'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='变动来源: checkin/spend/expire/adjust'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='该笔额度到期时间，spend/expire/adjust 通常为 NULL，checkin 有值'),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True, comment="幂等键，例如对于签到使用 'checkin:user_id:yyyy-mm-dd' 保证一天只能签到一次"),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='附加元数据'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='基于ULID生成的唯一标识'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['account_id'], ['credit_accounts.id'], name=op.f('fk_credit_transactions_account_id_credit_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_transactions_pkey'))
    )
    op.create_index('idx_credits_tx_idempotency', 'credit_transactions', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index(op.f('ix_credit_transactions_account_id'), 'credit_transactions', ['account_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联的用户ID'),
    sa.Column('chat_message_id', sa.UUID(), nullable=True, comment='关联的聊天消息ID'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='调用的大模型名称'),
    sa.Column('input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='输入 Token 数'),
    sa.Column('output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='输出 Token 数'),
    sa.Column('credit_cost', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='本次调用折算扣减的 Credits 额度'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='附加元数据'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='基于ULID生成的唯一标识'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], name=op.f('fk_usage_records_chat_message_id_chat_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('usage_records_pkey'))
    )
    op.create_index(op.f('ix_usage_records_chat_message_id'), 'usage_records', ['chat_message_id'], unique=False)
    op.create_index('idx_usage_records_chat_message_id_unique', 'usage_records', ['chat_message_id'], unique=True, postgresql_where=sa.text('chat_message_id IS NOT NULL'))
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index('idx_usage_records_chat_message_id_unique', table_name='usage_records', postgresql_where=sa.text('chat_message_id IS NOT NULL'))
    op.drop_index(op.f('ix_usage_records_chat_message_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_credit_transactions_account_id'), table_name='credit_transactions')
    op.drop_index('idx_credits_tx_idempotency', table_name='credit_transactions', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_credit_accounts_user_id'), table_name='credit_accounts')
    op.drop_table('credit_accounts')
    # ### end Alembic commands ###
