"""add token

Revision ID: 2207686616a6
Revises: bef7eff16f62
Create Date: 2026-02-28 23:12:55.487603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '2207686616a6'
down_revision: Union[str, Sequence[str], None] = 'bef7eff16f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('client_request_id', sa.String(length=64), nullable=True, comment='客户端生成的唯一请求 ID'))
    op.add_column('chat_messages', sa.Column('tokens_input', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='输入 Token 数'))
    op.add_column('chat_messages', sa.Column('tokens_output', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='输出 Token 数'))
    op.create_index('idx_msgs_client_req_id', 'chat_messages', ['client_request_id'], unique=True)
    op.add_column('users', sa.Column('max_tokens', sa.Integer(), server_default=sa.text('100000'), nullable=False, comment='用户 Token 总额度'))
    op.add_column('users', sa.Column('used_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='用户已消费 Token 数'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'used_tokens')
    op.drop_column('users', 'max_tokens')
    op.drop_index('idx_msgs_client_req_id', table_name='chat_messages')
    op.drop_column('chat_messages', 'tokens_output')
    op.drop_column('chat_messages', 'tokens_input')
    op.drop_column('chat_messages', 'client_request_id')
    # ### end Alembic commands ###
