"""change id to ulid

Revision ID: dbeec23fd8e2
Revises: 93e33503f942
Create Date: 2026-01-08 18:55:37.350750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbeec23fd8e2'
down_revision: Union[str, Sequence[str], None] = '93e33503f942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_new',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    
    # ### end Alembic commands ###
# 2. 存量数据搬迁 (Data Seeding)
    # 利用 SQL 直接在数据库内部完成转换，效率最高
    op.execute("""
        INSERT INTO user_new (id, username, email, old_id)
        SELECT 
            (lpad(to_hex(id), 32, '0')::uuid), -- 保持确定性转换
            username, 
            email, 
            id 
        FROM public.user
    """)
# 3. 原子重命名 (Atomic Switch)
    # 在 PostgreSQL 中，这些 RENAME 操作是在同一个事务锁中完成的
    op.rename_table('user', 'user_old')
    op.rename_table('user_new', 'user')
# 重新构建索引

    #op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_new_username'), 'user', ['username'], unique=True)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'user_new')
    op.rename_table('user_old', 'user')
    op.drop_table('user_new')
    #op.drop_index(op.f('ix_user_new_username'), table_name='user')

    # ### end Alembic commands ###
