"""empty message

Revision ID: bbbe93107bec
Revises: 7e69ae88028d
Create Date: 2026-01-27 00:27:24.930061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bbbe93107bec'
down_revision: Union[str, Sequence[str], None] = '7e69ae88028d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users1',
    sa.Column('username', sa.String(length=20), nullable=False, comment='B端登录唯一标识'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='基于ULID生成的唯一标识'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users1_email'), 'users1', ['email'], unique=True)
    op.create_index(op.f('ix_users1_id'), 'users1', ['id'], unique=False)
    op.create_index(op.f('ix_users1_username'), 'users1', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users1_username'), table_name='users1')
    op.drop_index(op.f('ix_users1_id'), table_name='users1')
    op.drop_index(op.f('ix_users1_email'), table_name='users1')
    op.drop_table('users1')
    # ### end Alembic commands ###
